version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: megasena-db
    environment:
      POSTGRES_USER: megasena_user
      POSTGRES_PASSWORD: megasena_password
      POSTGRES_DB: megasena_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
